export const LANGUAGES: { code: string; name: string }[] = [
  { code: "auto", name: "Automatisch erkennen" },
  { code: "de", name: "Deutsch" },
  { code: "en", name: "Englisch" },
  { code: "fr", name: "Französisch" },
  { code: "es", name: "Spanisch" },
  { code: "it", name: "Italienisch" },
  { code: "pt", name: "Portugiesisch" },
  { code: "nl", name: "Niederländisch" },
  { code: "pl", name: "Polnisch" },
  { code: "ru", name: "Russisch" },
  { code: "uk", name: "Ukrainisch" },
  { code: "tr", name: "Türkisch" },
  { code: "ar", name: "Arabisch" },
  { code: "he", name: "Hebräisch" },
  { code: "hi", name: "Hindi" },
  { code: "zh", name: "Chinesisch" },
  { code: "ja", name: "Japanisch" },
  { code: "ko", name: "Koreanisch" },
  { code: "vi", name: "Vietnamesisch" },
  { code: "th", name: "Thailändisch" },
  { code: "sv", name: "Schwedisch" },
  { code: "no", name: "Norwegisch" },
  { code: "da", name: "Dänisch" },
  { code: "fi", name: "Finnisch" },
  { code: "cs", name: "Tschechisch" },
  { code: "ro", name: "Rumänisch" },
  { code: "el", name: "Griechisch" },
];
